development:
  adapter: postgresql
  encoding: unicode
  database: ecommerce
  pool: 5
  username: bitlasoft
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ecommerce
  pool: 5
  username: bitlasoft
  password:
