# https://www.robinwieruch.de/postgres-sql-macos-setup/
development:
  adapter: postgresql
  encoding: unicode
  database: ecommerce
  pool: 5
  username: mutha
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ecommerce
  pool: 5
  username: mutha
  password:
